# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
stages:
- stage: DeployToVM
  jobs:
  - deployment: InstallApacheAndConfigure
    displayName: "Instalar Apache y Configurar Página"

    enviroment:
      name: "examen-VM"
      resourceType: VirtualMachine

      strategy:
        runOnce:
          deploy:
            steps:
            - scripts:
              echo: "Instalando Apache y configurando la página de prueba..."
              sudo apt-get update
              sudo apt install -y apache2
              echo 'automatizando el despliegue de maquina virtual desde azure devops' | sudo tee /var/www/html/index.html
              sudo systemctl restart apache2
              echo "Apache instalado y página de bienvenida configurada."
            displayName: "Instalar apache y configurar mensaje"
